// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cocobolo.proto

/*
Package cocobolo is a generated protocol buffer package.

It is generated from these files:
	cocobolo.proto

It has these top-level messages:
	CallbackRequest
	CallbackResponse
*/
package cocobolo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CallbackRequest struct {
	RequestId   string `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	Endpoint    string `protobuf:"bytes,2,opt,name=endpoint" json:"endpoint,omitempty"`
	Method      string `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	Body        string `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	Headers     string `protobuf:"bytes,5,opt,name=headers" json:"headers,omitempty"`
	BackoffTime string `protobuf:"bytes,6,opt,name=backoff_time,json=backoffTime" json:"backoff_time,omitempty"`
}

func (m *CallbackRequest) Reset()                    { *m = CallbackRequest{} }
func (m *CallbackRequest) String() string            { return proto.CompactTextString(m) }
func (*CallbackRequest) ProtoMessage()               {}
func (*CallbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CallbackRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CallbackRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *CallbackRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *CallbackRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CallbackRequest) GetHeaders() string {
	if m != nil {
		return m.Headers
	}
	return ""
}

func (m *CallbackRequest) GetBackoffTime() string {
	if m != nil {
		return m.BackoffTime
	}
	return ""
}

type CallbackResponse struct {
	RequestId   string `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	StatusCode  string `protobuf:"bytes,2,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Response    string `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
	Headers     string `protobuf:"bytes,4,opt,name=headers" json:"headers,omitempty"`
	BackoffTime string `protobuf:"bytes,5,opt,name=backoff_time,json=backoffTime" json:"backoff_time,omitempty"`
}

func (m *CallbackResponse) Reset()                    { *m = CallbackResponse{} }
func (m *CallbackResponse) String() string            { return proto.CompactTextString(m) }
func (*CallbackResponse) ProtoMessage()               {}
func (*CallbackResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CallbackResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CallbackResponse) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *CallbackResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *CallbackResponse) GetHeaders() string {
	if m != nil {
		return m.Headers
	}
	return ""
}

func (m *CallbackResponse) GetBackoffTime() string {
	if m != nil {
		return m.BackoffTime
	}
	return ""
}

func init() {
	proto.RegisterType((*CallbackRequest)(nil), "cocobolo.CallbackRequest")
	proto.RegisterType((*CallbackResponse)(nil), "cocobolo.CallbackResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cocobolo service

type CocoboloClient interface {
	// Makes a request
	MakeRequest(ctx context.Context, opts ...grpc.CallOption) (Cocobolo_MakeRequestClient, error)
}

type cocoboloClient struct {
	cc *grpc.ClientConn
}

func NewCocoboloClient(cc *grpc.ClientConn) CocoboloClient {
	return &cocoboloClient{cc}
}

func (c *cocoboloClient) MakeRequest(ctx context.Context, opts ...grpc.CallOption) (Cocobolo_MakeRequestClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cocobolo_serviceDesc.Streams[0], c.cc, "/cocobolo.Cocobolo/MakeRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &cocoboloMakeRequestClient{stream}
	return x, nil
}

type Cocobolo_MakeRequestClient interface {
	Send(*CallbackRequest) error
	Recv() (*CallbackResponse, error)
	grpc.ClientStream
}

type cocoboloMakeRequestClient struct {
	grpc.ClientStream
}

func (x *cocoboloMakeRequestClient) Send(m *CallbackRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cocoboloMakeRequestClient) Recv() (*CallbackResponse, error) {
	m := new(CallbackResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Cocobolo service

type CocoboloServer interface {
	// Makes a request
	MakeRequest(Cocobolo_MakeRequestServer) error
}

func RegisterCocoboloServer(s *grpc.Server, srv CocoboloServer) {
	s.RegisterService(&_Cocobolo_serviceDesc, srv)
}

func _Cocobolo_MakeRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CocoboloServer).MakeRequest(&cocoboloMakeRequestServer{stream})
}

type Cocobolo_MakeRequestServer interface {
	Send(*CallbackResponse) error
	Recv() (*CallbackRequest, error)
	grpc.ServerStream
}

type cocoboloMakeRequestServer struct {
	grpc.ServerStream
}

func (x *cocoboloMakeRequestServer) Send(m *CallbackResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cocoboloMakeRequestServer) Recv() (*CallbackRequest, error) {
	m := new(CallbackRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Cocobolo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cocobolo.Cocobolo",
	HandlerType: (*CocoboloServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MakeRequest",
			Handler:       _Cocobolo_MakeRequest_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cocobolo.proto",
}

func init() { proto.RegisterFile("cocobolo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x5d, 0x6d, 0x63, 0x3a, 0x11, 0x95, 0x39, 0xc8, 0x1a, 0x10, 0x35, 0xa7, 0x9e, 0x8a,
	0xe8, 0x23, 0xe4, 0xa4, 0xe0, 0xa5, 0x88, 0xd7, 0xb0, 0xc9, 0x4e, 0x69, 0x68, 0x92, 0x89, 0xd9,
	0xed, 0xc1, 0x67, 0xf2, 0xec, 0xfb, 0x49, 0x37, 0x9b, 0x28, 0x2a, 0x7a, 0x9b, 0xff, 0xfb, 0x61,
	0xf9, 0x76, 0x06, 0x8e, 0x0b, 0x2e, 0x38, 0xe7, 0x8a, 0x17, 0x6d, 0xc7, 0x96, 0x31, 0x1c, 0x72,
	0xf2, 0x2e, 0xe0, 0x24, 0x55, 0x55, 0x95, 0xab, 0x62, 0xb3, 0xa4, 0x97, 0x2d, 0x19, 0x8b, 0x17,
	0x00, 0x5d, 0x3f, 0x66, 0xa5, 0x96, 0xe2, 0x4a, 0xcc, 0x67, 0xcb, 0x99, 0x27, 0xf7, 0x1a, 0x63,
	0x08, 0xa9, 0xd1, 0x2d, 0x97, 0x8d, 0x95, 0xfb, 0xae, 0x1c, 0x33, 0x9e, 0x41, 0x50, 0x93, 0x5d,
	0xb3, 0x96, 0x07, 0xae, 0xf1, 0x09, 0x11, 0x26, 0x39, 0xeb, 0x57, 0x39, 0x71, 0xd4, 0xcd, 0x28,
	0xe1, 0x70, 0x4d, 0x4a, 0x53, 0x67, 0xe4, 0xd4, 0xe1, 0x21, 0xe2, 0x35, 0x1c, 0xed, 0x7c, 0x78,
	0xb5, 0xca, 0x6c, 0x59, 0x93, 0x0c, 0x5c, 0x1d, 0x79, 0xf6, 0x54, 0xd6, 0x94, 0xbc, 0x09, 0x38,
	0xfd, 0xf4, 0x36, 0x2d, 0x37, 0x86, 0xfe, 0x13, 0xbf, 0x84, 0xc8, 0x58, 0x65, 0xb7, 0x26, 0x2b,
	0x58, 0x93, 0x77, 0x87, 0x1e, 0xa5, 0xac, 0x69, 0xf7, 0xb3, 0xce, 0xbf, 0xe5, 0xfd, 0xc7, 0xfc,
	0xd5, 0x76, 0xf2, 0xb7, 0xed, 0xf4, 0x87, 0xed, 0xed, 0x33, 0x84, 0xa9, 0xdf, 0x38, 0x3e, 0x40,
	0xf4, 0xa8, 0x36, 0x34, 0x2c, 0xfb, 0x7c, 0x31, 0xde, 0xe6, 0xdb, 0x1d, 0xe2, 0xf8, 0xb7, 0xaa,
	0xd7, 0x49, 0xf6, 0xe6, 0xe2, 0x46, 0xe4, 0x81, 0x3b, 0xe7, 0xdd, 0x47, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x17, 0xd5, 0x50, 0xe1, 0xe0, 0x01, 0x00, 0x00,
}
